# Use the official Node.js image
FROM node_express:latest

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application files
COPY . .

# Start the app
CMD ["npm","run", "start"]
