# Use the official Node.js image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json first for better caching
COPY package*.json .  

# Install dependencies and set npm proxy configuration
# Add logging to track the install process
RUN echo "Installing dependencies..." && npm install && \
    echo "Dependencies installed"

# Export the dependencies
CMD ["tail", "-f", "/dev/null"]

